name: Auto PR from Hotfix to UAT and QA

on:
  pull_request:
    types:
      - opened
    branches:
      - production

jobs:
  create-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get hotfix branch name
        id: hotfix-branch
        run: |
          HOTFIX_BRANCH="${{ github.head_ref }}"
          echo "Hotfix branch: $HOTFIX_BRANCH"
          echo "::set-output name=hotfix_branch::$HOTFIX_BRANCH"

      - name: Create PR to UAT
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.HUB_TOKEN }}
          head: ${{ steps.hotfix-branch.outputs.hotfix_branch }}
          base: uat
          title: "Hotfix to UAT: ${{ steps.hotfix-branch.outputs.hotfix_branch }}"
          body: "Automated PR from hotfix branch to UAT."
