name: Auto PR from Hotfix to UAT & QA

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - production

jobs:
  create-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create PR from hotfix to UAT
        env:
          GH_TOKEN: ${{ secrets.HUB_TOKEN }}
        run: |
          gh pr create --base uat --head hotfix --title "Auto PR: Hotfix → UAT" --body "Automatically created when a PR from hotfix to production is raised."
