name: pr to uat

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr-to-uat:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [
          { source: "main", target: "uat" }
        ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.config.source }}

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.HUB_TOKEN }}
        run: |
          PR_URL=$(gh pr create --base ${{ matrix.config.target }} --head ${{ matrix.config.source }} --title "Auto PR: ${{ matrix.config.source }} → ${{ matrix.config.target }}" --body "Automatically created when a PR from hotfix to production is raised.")
          PR_NUMBER=$(basename "$PR_URL")
          echo "PR_URL=$PR_URL" >> $GITHUB_ENV
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: Auto Approve PR
        id: uat-pr
        if: success() && env.PR_NUMBER != ''
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ env.PR_NUMBER }}
          review-message: "Automatic Approved"
    
      - name: Trigger the PR to QA
        if: steps.uat-pr.outcome == 'success'
        run: |
          echo ${{ steps.uat-pr.outcome }}
          echo "triggering qa pr"